### ISSUE TITLE
(InCooldownPeriod) Help Please

### ISSUE THREAD

**Issue by Kievtek** [finndev/PokeBuddy#19] opened 2016-07-29 18:02 UTC
[Farm Pokestops] InCooldownPeriod -> Received XP: 0 dont move,always freeze in this part ...Help Please

**Comment by bfikree** [comment] 2016-07-29 20:27
If you just spoofed you're currently soft banned, the bot tries to break the ban by spinning one stop over and over again until the server recognizes the new location as accurate.

**Comment by Kievtek** [comment] 2016-07-29 20:42
i have this problem 24hours and many accounts diferenty, i tested 4 accounts to comprove soft ban or not,always has same problem.

**Comment by Vanethir** [comment] 2016-07-29 20:42
[Duplicate of #6]
Try to keep all information together, so it gets easier to find and fix problems.

**Closed** 2016-07-31 23:50 UTC
Labels: bug, duplicate
