### ISSUE TITLE
Potions Problem

### ISSUE THREAD

**Issue by LuzgGO** [finndev/PokeBuddy#97] opened 2016-08-01 01:43 UTC
The new update is deleting all my potions, Hyper and max potions if I select, "recycle itens", and also is transferring good pokemons with CP 1000+, it tranferred my favorite Clefabe CP 1300 and my growlite, please fix this

**Comment by A-Charvin** [comment] 2016-08-01 03:27
The issue is still prevailing or is it resolved as of now?

**Comment by LuzgGO** [comment] 2016-08-01 03:35
its prevailing, I will wait until the next update

**Comment by bfikree** [comment] 2016-08-01 13:01
Can confirm that it transferred all of my potions and transferred an 1131 Electabuzz

**Comment by Vanethir** [comment] 2016-08-01 17:45
Potion/Revive transfer should be less aggresive now. Dont know exact number though. So still be careful with a high amount of potions/Revives you might want to keep.

**Comment by Vanethir** [comment] 2016-08-01 19:59
You can now freely set what (and how many) you want to keep of each item.

**Closed** 2016-08-01 20:07 UTC
Labels: bug
