### ISSUE TITLE
Are you kidding, right?

### ISSUE THREAD

**Issue by stilesit** [finndev/PokeBuddy#180] opened 2016-08-02 23:01 UTC
Today I just lost almost all my items and half of my pokémons with +1000 CP because it has transferred it as "bad pokemon", are you crazy? Wth did you do on this last update? Even if I check it in "do not transfer" list, it keep transferring! Please bring back the old version, which had no "transfer", "evolve" and "recycle items" list, and had the old internal list of "bad pokemons" and "good pokemons" of ~2days ago, in the old version I was getting 40k XP per hour, getting ride of really bad pokemons and keeping the good (even some "weak" but I transfered it after with no problems, like bulbasaur with 500 XP or eevee with 200), everything was perfect.

**Comment by Ronixl** [comment] 2016-08-02 23:50
I agree. Or the developer needs to add a way for the user to enter the parameters of what a "bad" pokemon is

**Comment by dr3m1** [comment] 2016-08-02 23:54
It's a 100% free bot, so ungrateful. Don't like it? Don't use it.

**Comment by PDeception** [comment] 2016-08-03 00:00
This hasn't happened to me, and im using the latest version. Although, I guess to prevent this temporarily, go into the settings and check off your most valuable pokemon in the "do not transfer" box.

However, this bot is not the most configurable one out there, and you should not be trying to use it like one. This bot is the most easiest one to set up, with a smooth interface.

**Comment by Ronixl** [comment] 2016-08-03 00:07
I'm not trying to bash the developer. The interface is the most professional one out there. I'm only trying saying what I said to make the bot better.

**Comment by stilesit** [comment] 2016-08-03 00:16
Ronixl Yes! I'm also not trying to bash him, but considering my experience with the bot a few days ago and now, I prefer the old version or funcional features without those bugs what get losses/damages. I don't have complaines about the design, it's perfect.

**Comment by PDeception** [comment] 2016-08-03 00:18
Please provide the version you were using, copy the log, and paste it into a notepad. In the second row, it says the version.

**Comment by stilesit** [comment] 2016-08-03 00:40
PDception, version 0.0.3.4, but it updates automatically when opened.

**Comment by lordofthereef** [comment] 2016-08-03 02:51
The problem isn't constructive criticism, it's how you said it. People here tend to be helpful. Part of the reason why people called you on it is because you were a straight up dick about how you presented yourself. I'd say I am sorry for your loss but...

**Comment by 404unknown** [comment] 2016-08-03 05:37
Please be polite, the developer is constantly bringing out new updates daily for free, and you are not even bringing out constructive criticism, you just straight out ask the dev to reverse everything. We have a friendly and helpful community here, we dont need people like you here spreading salt. No one is willing to help you if you are such a dick  "Are you crazy?", "I'm also not trying to bash him"

**Comment by aniketk11** [comment] 2016-08-03 09:12
@stilesit Always respect the developer! Are you a first timer at development forums? If you are you don't have a clue what effort hes taking. Its not supposed to be smooth and flawless like you want it to be when its under development. Its BETA for a reason. No one cares about your pokemons. Use some other bot instead.

**Comment by therealpequod** [comment] 2016-08-03 10:37
You are an ungrateful bitch

**Comment by Vanethir** [comment] 2016-08-03 12:16
Will close this issue because it's just about complaining on each side. :)
We are sorry for any losses you may experienced. Please consider PokeBuddy is still in Beta though. 

Also mark your Pokemon as favorite to assure they won't be transferred by PokeBuddys **Transfer bad Pokemon** option.

For any updates concerning this problem check #116.

**Closed by Vanethir** 2016-08-03 12:16 UTC
Labels: bug, duplicate
