### ISSUE TITLE
The update says "Settings menu changed. Now everything is configurable" but its still the same!

### ISSUE THREAD

**Issue by aniketk11** [finndev/PokeBuddy#207] opened 2016-08-03 14:00 UTC
I see no configuration options anywhere.

**Comment by Vanethir** [comment] 2016-08-03 14:07
First of all: Be careful with the **Transfer Bad Pokemon** option and **Transfer list**. It isn't working as intended... tbh it isn't working at all. It will just keep your highest CP of each kind.

**Evolution** + **Item** Features should work as intended: In your main windows choose **Settings** -> **Pokemon Settings** to set your evolution list.
For Item settings choose **Settings**->**Item Settings**. There you can change all your items and the quantity you want to keep.

**Comment by MikeTheory** [comment] 2016-08-03 14:49
@Vanethir Is there a way to find out when the transferring issue will be fixed? Like, when it's updated, is there a place on the site that will announce it?

**Comment by Vanethir** [comment] 2016-08-03 15:34
Will announce it in #116. Most bugreports will be closed after fixing it, too. ~40% Transferlist bugreports + ~40% CatchError Bugreports (if you are out of normal Pokeballs). :)

**Closed** 2016-08-03 16:55 UTC
Labels: question
